---
# Assumptions:
#  - KUBECONFIG env var is set on orchestration host (would have to be in bashrc) or kubeconfig is set in ~/.kube/config
#  - cluster-logging operator deployed
#  - podman installed
#  - libselinux-python2 (or variation depending on OS) installed
- name: Run logging test
  hosts: localhost
  remote_user: "{{orchestration_user}}"
  vars_files:
    - vars/logging.yml
  tasks:
    - name: Verify oc command is available
      command: oc version
      changed_when: False
    - name: Verify openshift-logging exists
      shell: oc get projects | grep "openshift-logging"
      changed_when: False
    - name: Verify ElasticSearch pods exist
      shell: oc get pods -n openshift-logging | grep elasticsearch
      changed_when: False
    - name: Get ElasticSearch pod to query from
      shell: oc get pods -n openshift-logging | grep elasticsearch | grep Running | head -n 1 | awk '{print $1}'
      register: es_pod
      changed_when: False
      tags:
        - delete_indices
    - name: Delete existing logtest indices
      shell: |
        BASE_CMD="oc exec -n openshift-logging -c elasticsearch {{ es_pod.stdout }} -- es_util"
        ${BASE_CMD} --query=app* -XDELETE;
      tags:
        - delete_indices
    - name: Delete existing collector buffers
      shell: |
        for p in $(oc -n openshift-logging get pods -l component=fluentd -o jsonpath={.items[*].metadata.name}); do oc exec $p -- rm -rf /var/lib/fluentd/** ;done;
    - name: Get worker nodes
      shell: oc get nodes | grep worker | awk '{print $1}'
      register: worker_nodes
      changed_when: False
    - name: Label single worker node
      block:
        - name: Remove any existing "placement" labels from worker nodes
          shell: "oc label node {{ item }} placement-"
          loop: "{{ worker_nodes.stdout_lines }}"
          register: result
          changed_when: '"not labeled" not in result.stdout'
        - name: Label one worker node with placement=logtest
          shell: oc label node $(oc get nodes | grep worker | head -n 1 | awk '{print $1}') placement=logtest
      when: not LABAL_ALL_NODES
      tags: label_node
    - name: Label all nodes
      shell: "for i in $(oc get nodes | grep worker | awk '{print $1}'); do oc label node/$i placement=logtest --overwrite; done"
      when: LABAL_ALL_NODES
      tags: label_node
    - name: Create workloads directory
      file:
        path: workloads
        state: directory
        mode: '0755'
    - name: Template cluster-loader logtest logging config file
      template:
        src: templates/logtest.yml.j2
        dest: workloads/logtest.yml
    - name: Template logtest-rc.json
      template:
        src: templates/logtest-rc.json.j2
        dest: workloads/logtest-rc.json
    - name: Podman pull cluster-loader image
      podman_image:
        name: quay.io/openshift/origin-tests
        tag: "{{ORIGIN_TESTS_VERSION}}"
    - name: Launch cluster-loader
      shell: |
        podman run --rm \
        -v {{ ansible_facts['env']['KUBECONFIG']|default(ansible_facts['env']['PWD'] + '/.kube/config') }}:/root/.kube/config:z \
        -v {{ansible_facts['env']['PWD']}}/workloads/:/root/workloads/:z \
        -i quay.io/openshift/origin-tests:{{ORIGIN_TESTS_VERSION}} \
        /bin/bash -c 'export KUBECONFIG=/root/.kube/config && \
        export VIPERCONFIG=/root/workloads/logtest.yml && \
        openshift-tests run-test "{{ CLUSTER_LOADER_STRING }} concurrently with templates [Suite:openshift]"' \
        |& tee workloads/cluster-loader.log
    - set_fact:
        test_start: "{{ lookup('pipe','date +%s') }}"
    - name: Pause for est. time of test {{ (NUM_LINES|int / RATE|int) | round(0, 'floor') | int }} min
      pause:
        minutes: "{{ (NUM_LINES|int / RATE|int) | round(0, 'floor') | int }}"
    - name: Check for test completion for up to {{ PAUSE_OFFSET }} min
      shell: x=0; for i in $(oc exec -n openshift-logging {{ es_pod.stdout }} -c elasticsearch -- es_util --query='_cat/indices'| grep 'app' | awk '{print $7}'); do (( x += i )); done; echo "$x"
      register: num_indexed
      until: num_indexed.stdout|int  >=  (NUM_LINES|int) * (NUM_PROJECTS|int)
      retries: "{{ (60 * PAUSE_OFFSET | int) }}"
      delay: 1
    - set_fact:
        test_end: "{{ lookup('pipe','date +%s') }}"
    - name: Clean up logtest projects
      shell: oc delete project $(oc get projects | grep '{{ PROJECT_BASENAME }}' | awk '{print $1}' | sed ':a;N;$!ba;s/\n/ /g')
      tags:
        - cleanup
    - name: Test Runtime
      debug: msg="{{ test_end | int - test_start | int }} sec"
